### ISSUE TITLE
Boot/reboot/shutdown splash screen

### ISSUE THREAD

**Issue by agherzan** [resin-os/resin-via-arm#4]
# Steps to reproduce issue 
Connect to the HDMI connected to a monitor
Boot the device

# Expected result 
Resin logo splash screen should be visible

# Actual result 
Resin logo is not displayed (at least in my setup, where the hdmi monitor displays the signal a little late)

Later edit: The HDMI monitor receives no signal

# Other information 
Reported by: Florin Sarbu 

Test configuration: VIA VAB820 

Test case number: TC07 

Test run: [https://resinio.testlodge.com/projects/16238/runs/196239?tab=2&run_section_id=176153&executed_case_id=9459439#executed_case_9459439](https://resinio.testlodge.com/projects/16238/runs/196239?tab=2&run_section_id=176153&executed_case_id=9459439#executed_case_9459439)

**Comment by floion** [comment]
Also, at shutdown/reboot the resin logo is displayed but not fullscreen as expected

**Comment by agherzan** [comment]
This issue was moved to resin-os/resinos#36
